version: "3.8"

services:
  # MongoDB Service
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # Redis Service
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Zookeeper Service (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  # Backend Service (Node.js + Express)
  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - mongo
      - redis
      - kafka
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:example@mongo:27017
      REDIS_HOST: redis
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./backend:/app
    command: ["npm", "start"]

  # Frontend Service (React + Vite)
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      REACT_APP_BACKEND_URL: http://backend:5000
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  # Nginx (Reverse Proxy)
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo_data:
  redis_data:
